// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using XcavateBuckets.Domain.Data;

#nullable disable

namespace XcavateBuckets.Domain.Migrations
{
    [DbContext(typeof(BucketDbContext))]
    [Migration("20260725135834_InitBuckets")]
    partial class InitBuckets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("XcavateBuckets.Domain.Entities.Bucket", b =>
                {
                    b.Property<long>("BucketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BucketId"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Creator")
                        .HasColumnType("text");

                    b.Property<string>("EncryptionKey")
                        .HasColumnType("text");

                    b.Property<bool>("IsWritable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long>("NamespaceId")
                        .HasColumnType("bigint");

                    b.Property<long>("NextMessageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Properties")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BucketId");

                    b.HasIndex("NamespaceId");

                    b.ToTable("buckets", (string)null);
                });

            modelBuilder.Entity("XcavateBuckets.Domain.Entities.BucketAdmin", b =>
                {
                    b.Property<long>("BucketId")
                        .HasColumnType("bigint");

                    b.Property<string>("SubjectId")
                        .HasColumnType("text");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BucketId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("bucket_admins", (string)null);
                });

            modelBuilder.Entity("XcavateBuckets.Domain.Entities.BucketContributor", b =>
                {
                    b.Property<long>("BucketId")
                        .HasColumnType("bigint");

                    b.Property<string>("SubjectId")
                        .HasColumnType("text");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BucketId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("bucket_contributors", (string)null);
                });

            modelBuilder.Entity("XcavateBuckets.Domain.Entities.BucketViewer", b =>
                {
                    b.Property<long>("BucketId")
                        .HasColumnType("bigint");

                    b.Property<string>("ViewerId")
                        .HasColumnType("text");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BucketId", "ViewerId");

                    b.HasIndex("ViewerId");

                    b.ToTable("bucket_viewers", (string)null);
                });

            modelBuilder.Entity("XcavateBuckets.Domain.Entities.Message", b =>
                {
                    b.Property<long>("BucketId")
                        .HasColumnType("bigint");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentHash")
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<string>("Contributor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("IpfsContent")
                        .HasColumnType("text");

                    b.Property<string>("Properties")
                        .HasColumnType("jsonb");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<string>("Tag")
                        .HasColumnType("text");

                    b.HasKey("BucketId", "MessageId");

                    b.HasIndex("Contributor");

                    b.HasIndex("MessageId");

                    b.HasIndex("Tag");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("XcavateBuckets.Domain.Entities.Namespace", b =>
                {
                    b.Property<long>("NamespaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("NamespaceId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Creator")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Properties")
                        .HasColumnType("jsonb");

                    b.Property<string>("SchemaUri")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("NamespaceId");

                    b.ToTable("namespaces", (string)null);
                });

            modelBuilder.Entity("XcavateBuckets.Domain.Entities.NamespaceManager", b =>
                {
                    b.Property<long>("NamespaceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Manager")
                        .HasColumnType("text");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("NamespaceId", "Manager");

                    b.HasIndex("Manager");

                    b.ToTable("namespace_managers", (string)null);
                });

            modelBuilder.Entity("XcavateBuckets.Domain.Entities.Tag", b =>
                {
                    b.Property<long>("BucketId")
                        .HasColumnType("bigint");

                    b.Property<string>("TagName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Creator")
                        .HasColumnType("text");

                    b.HasKey("BucketId", "TagName");

                    b.HasIndex("TagName");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("XcavateBuckets.Domain.Entities.TagMessageCount", b =>
                {
                    b.Property<long>("BucketId")
                        .HasColumnType("bigint");

                    b.Property<string>("TagName")
                        .HasColumnType("text");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BucketId", "TagName");

                    b.HasIndex("TagName");

                    b.ToTable("tag_message_counts", (string)null);
                });

            modelBuilder.Entity("XcavateBuckets.Domain.Entities.Bucket", b =>
                {
                    b.HasOne("XcavateBuckets.Domain.Entities.Namespace", "Namespace")
                        .WithMany("Buckets")
                        .HasForeignKey("NamespaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Namespace");
                });

            modelBuilder.Entity("XcavateBuckets.Domain.Entities.BucketAdmin", b =>
                {
                    b.HasOne("XcavateBuckets.Domain.Entities.Bucket", "Bucket")
                        .WithMany("Admins")
                        .HasForeignKey("BucketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bucket");
                });

            modelBuilder.Entity("XcavateBuckets.Domain.Entities.BucketContributor", b =>
                {
                    b.HasOne("XcavateBuckets.Domain.Entities.Bucket", "Bucket")
                        .WithMany("Contributors")
                        .HasForeignKey("BucketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bucket");
                });

            modelBuilder.Entity("XcavateBuckets.Domain.Entities.BucketViewer", b =>
                {
                    b.HasOne("XcavateBuckets.Domain.Entities.Bucket", "Bucket")
                        .WithMany("Viewers")
                        .HasForeignKey("BucketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bucket");
                });

            modelBuilder.Entity("XcavateBuckets.Domain.Entities.Message", b =>
                {
                    b.HasOne("XcavateBuckets.Domain.Entities.Bucket", "Bucket")
                        .WithMany("Messages")
                        .HasForeignKey("BucketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bucket");
                });

            modelBuilder.Entity("XcavateBuckets.Domain.Entities.NamespaceManager", b =>
                {
                    b.HasOne("XcavateBuckets.Domain.Entities.Namespace", "Namespace")
                        .WithMany("Managers")
                        .HasForeignKey("NamespaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Namespace");
                });

            modelBuilder.Entity("XcavateBuckets.Domain.Entities.Tag", b =>
                {
                    b.HasOne("XcavateBuckets.Domain.Entities.Bucket", "Bucket")
                        .WithMany("Tags")
                        .HasForeignKey("BucketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bucket");
                });

            modelBuilder.Entity("XcavateBuckets.Domain.Entities.TagMessageCount", b =>
                {
                    b.HasOne("XcavateBuckets.Domain.Entities.Bucket", "Bucket")
                        .WithMany()
                        .HasForeignKey("BucketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bucket");
                });

            modelBuilder.Entity("XcavateBuckets.Domain.Entities.Bucket", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("Contributors");

                    b.Navigation("Messages");

                    b.Navigation("Tags");

                    b.Navigation("Viewers");
                });

            modelBuilder.Entity("XcavateBuckets.Domain.Entities.Namespace", b =>
                {
                    b.Navigation("Buckets");

                    b.Navigation("Managers");
                });
#pragma warning restore 612, 618
        }
    }
}
