// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using XcavateProfileApi.Data;

#nullable disable

namespace XcavateProfileApi.Migrations
{
    [DbContext(typeof(ProfileDbContext))]
    [Migration("20260801163836_AddWalletMigrations")]
    partial class AddWalletMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("XcavateProfile.Client.Profile", b =>
                {
                    b.Property<string>("Ss58Address")
                        .HasColumnType("text")
                        .HasJsonPropertyName("ss58address");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasJsonPropertyName("bio");

                    b.Property<string>("Nickname")
                        .HasColumnType("text")
                        .HasJsonPropertyName("nickname");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text")
                        .HasJsonPropertyName("profilePicture");

                    b.Property<string>("X25519Key")
                        .HasColumnType("text")
                        .HasJsonPropertyName("x25519Key");

                    b.HasKey("Ss58Address");

                    b.HasIndex("Nickname")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("XcavateProfile.Client.WalletMigration", b =>
                {
                    b.Property<string>("Ss58Address")
                        .HasColumnType("text")
                        .HasJsonPropertyName("ss58address");

                    b.Property<string>("SolanaAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("solanaAddress");

                    b.HasKey("Ss58Address");

                    b.ToTable("WalletMigrations");
                });
#pragma warning restore 612, 618
        }
    }
}
