// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using XcavateProfileApi.Data;

#nullable disable

namespace XcavateProfileApi.Migrations
{
    [DbContext(typeof(ProfileDbContext))]
    [Migration("20260818171955_AddUserAttributesAndCompanies")]
    partial class AddUserAttributesAndCompanies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("XcavateProfile.Client.Company", b =>
                {
                    b.Property<string>("CompanyId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasJsonPropertyName("companyId");

                    b.Property<string>("Address")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasJsonPropertyName("address");

                    b.Property<string>("CompanyWalletAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasJsonPropertyName("companyWalletAddress");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("createdAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasJsonPropertyName("email");

                    b.Property<string>("Logo")
                        .HasColumnType("text")
                        .HasJsonPropertyName("logo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasJsonPropertyName("name");

                    b.Property<string>("Permission")
                        .HasColumnType("text")
                        .HasJsonPropertyName("permission");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasJsonPropertyName("summary");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("updatedAt");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasJsonPropertyName("userId");

                    b.Property<string>("Website")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasJsonPropertyName("website");

                    b.HasKey("CompanyId");

                    b.HasIndex("CompanyWalletAddress");

                    b.HasIndex("UserId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("XcavateProfile.Client.Profile", b =>
                {
                    b.Property<string>("Ss58Address")
                        .HasColumnType("text")
                        .HasJsonPropertyName("ss58address");

                    b.Property<string>("Address")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasJsonPropertyName("address");

                    b.Property<string>("Background")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasJsonPropertyName("background");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasJsonPropertyName("bio");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("createdAt");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasJsonPropertyName("email");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasJsonPropertyName("name");

                    b.Property<string>("Nickname")
                        .HasColumnType("text")
                        .HasJsonPropertyName("nickname");

                    b.Property<string>("Permission")
                        .HasColumnType("text")
                        .HasJsonPropertyName("permission");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasJsonPropertyName("phone");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text")
                        .HasJsonPropertyName("profilePicture");

                    b.Property<string>("Roles")
                        .HasColumnType("text")
                        .HasJsonPropertyName("roles");

                    b.Property<string>("Title")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasJsonPropertyName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("updatedAt");

                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasJsonPropertyName("userId");

                    b.Property<string>("X25519Key")
                        .HasColumnType("text")
                        .HasJsonPropertyName("x25519Key");

                    b.HasKey("Ss58Address");

                    b.HasIndex("Nickname")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("XcavateProfile.Client.WalletMigration", b =>
                {
                    b.Property<string>("Ss58Address")
                        .HasColumnType("text")
                        .HasJsonPropertyName("ss58address");

                    b.Property<string>("SolanaAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("solanaAddress");

                    b.HasKey("Ss58Address");

                    b.ToTable("WalletMigrations");
                });
#pragma warning restore 612, 618
        }
    }
}
